name: glips
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: dennougorilla <dennougorilla@gmail.com>

environment:
  sdk: '>=2.5.0-dev.1.0 <3.0.0'

dependencies:
  image: ^2.1.4
  sass_builder: ^2.0.0
  js: any
  angular: ^6.0.0-alpha+1
  angular_components: 0.14.0-alpha+1
  build_config: '>=0.2.6 <0.5.0'

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.0.0-alpha.0
  pedantic: ^1.0.0
  test: ^1.5.1
